import './globals.css'
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] }) //tipo de fuente que saca de google

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <div>aca va a estar el navbar</div>
      {/* <body >{children}</body> */}
    </html>
  )
}
